
// Auto-generated by AutoPilot on 28-07-2023 at 21:30:13


const express = require("express");
const router = express.Router();

// Route to cook Pringles with sour cream
router.get("/pringles/sourCream", (req, res) => {
    res.send("Instructions to cook Pringles with sour cream: \n1. Preheat the oven to 350°F. \n2. Place Pringles on a baking sheet. \n3. Top Pringles with sour cream. \n4. Bake in preheated oven for 5 minutes. \n5. Enjoy your Pringles with sour cream!");
});

module.exports = router;