
// Auto-generated by AutoPilot on 28-07-2023 at 23:43:26

const express = require('express');
const router = express.Router();

// Route to generate cube from a number 
router.get('/asfas', (req, res) => {
    const number = req.query.number;
    // Cube the number
    const result = number * number * number;

    // Return result in JSON format
    if (result) {
        res.status(200).json({ result });
    } else {
        res.status(500).json({ error: 'Encountered an error' });
    }
});

module.exports = router;