
// Auto-generated by AutoPilot on 06-08-2023 at 19:27:22

const express = require('express');
const router = express.Router();

//Cube the number passed in the query param 'number'
//Return a JSON object with result or error
router.get('/test/ai/controller', (req, res) => {
  const number = req.query.number;
  if (number) {
    const result = Math.pow(number, 3);
    res.status(200).json({ result });
  } else {
    res.status(500).json({ error: 'Encountered an error' });
  }
});

module.exports = router;